Rails.application.routes.draw do
  root 'static_pages#home'

  get '/help',    to: 'static_pages#help'
  get '/about',   to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'

  get '/signup', to: 'users#new'
end

# memo:
# `get 'static_pages/help'`
# is equivalent to
# `get 'static_pages/help', to: 'static_pages#help'`
# and following helper methods are automatically generated by Rails when setting up the route:
# `static_pages_help_path` => `/help`
# `static_pages_help_url` => `http://www.example.com/help`
#
#
# `get '/help',    to: 'static_pages#help'`
# => helper_method: `help_(url/path)`
#
# help_path: '/help'
# help_url: 'http://www.example.com/help'
#
#
# if you want to change the helper method name, you can do so by passing `as` option:
# `get '/help', to: 'static_pages#help', as: 'helful'`
# => helper_method: `helful_(url/path)`
#
# helful_path: '/help'
# helful_url: 'http://www.example.com/help'
